- README.md
- challengeutils/challenge.py
- challengeutils/createchallenge.py
- challengeutils/evaluation_queue.py
- challengeutils/helpers.py
- challengeutils/mirrorwiki.py
- challengeutils/permissions.py
- challengeutils/utils.py
* Convert tabs to spaces
* Use new DREAM template
> Merge Dev into Master

- challengeutils/utils.py
> linting and return invite

- .gitignore
- README.md
- challengeutils/__init__.py
- challengeutils/__main__.py
- challengeutils/createchallenge.py
- setup.py
> Upgrade create challenge tool

- challengeutils/__main__.py
- challengeutils/utils.py
Resolve #38 
* Partial linting of functions
> Add parameter to allow for query results to be written to file

- Dockerfile
- Dockerfile.dev
> Fix docker file so always copying the most recent files

- challengeutils/__main__.py
- challengeutils/utils.py
- tests/test_utils.py
* List evaluations
* download submission
* annotation submission
> Challenge tools

- challengeutils/project_submission.py
- tests/test_project_submission.py
Added joining of two evaluation queues.  This is the test for it.
> Test for joining of two evaluation queues

- challengeutils/utils.py
Change the name of the function to indicate that it does not just return the ID, it returns a challenge object. Update the docstring to link to the definition of that object.
> update get challenge function

- challengeutils/discussion.py
The API call is already tested.
> Create thread reply convenience function

- challengeutils/__init__.py
> add public exports to namespace

- bin/runqueue.py
- scoring_harness/base_processor.py
- scoring_harness/messages.py
- scoring_harness/queue_scorer.py
- scoring_harness/queue_validator.py
- templates/challenge_config.template.py
> Update email and notification framework

- challengeutils/__main__.py
- challengeutils/evaluation_queue.py
- tests/test_evaluation_queue.py
* Create SubmissionQuota object
* Create cli to set evaluation quota
* Create convenience function to set evaluation quota
> Helper function to set evaluation queue quota

- challengeutils/utils.py
> Remove invite member to team functionality

- .github/workflows/pythonapp.yml
- challengeutils/evaluation_queue.py
- tests/synapseservices/test_challenge_obj.py
- tests/test_challenge.py
#43 
* Fix tests such that code coverage will run
* Add automation of code coverage in github action
* `__init__.py` must be present in `tests/`: http://thomas-cokelaer.info/blog/2017/01/pytest-cov-collects-no-data-on-travis/
> Automate code coverage

- challengeutils/__main__.py
- challengeutils/utils.py
- tests/test_utils.py
Convenience function to delete a submission
> Add in function to delete submission

- challengeutils/discussion.py
- challengeutils/synapseservices/discussion.py
- tests/test_discussion.py
> Add reply service

- challengeutils/discussion.py
- challengeutils/synapseservices/discussion.py
- tests/test_discussion.py
> Add thread service

- challengeutils/project_submission.py
- tests/test_project_submission.py
* Update project submission validation to return standard dict
* Make sure error strings are returned
> Patch project sub

- challengeutils/annotations.py
- tests/test_annotations.py
Add in convenience function to annotate submission with dictionary.
> Add annotate sub

- challengeutils/utils.py
- tests/test_utils.py
This function will allow admins of teams to remove members or the particular member to remove themselves from a team.
> Add in function to remove members from team

- requirements.txt
- setup.py
- tests/test_processor.py
- tests/test_scorer.py
- tests/test_validator.py
There are new features in synapse client that are only available after v2.2.0
> update synapse to at least v2.2.0

- challengeutils/__main__.py
- setup.py
Utilize new synapseclient version which reads in AUTH_TOKEN env variable to login
> Update syn login

- challengeutils/__main__.py
> fix UnboundLocalError when calling `valid` in command_validate_docker

- challengeutils/__main__.py
- challengeutils/createchallenge.py
- challengeutils/permissions.py
- tests/test_createchallenge.py
> Give Organizers team "Moderate"-level access to live project

- .github/workflows/pythonapp.yml
- requirements.txt
- setup.cfg
Add support for the new python version
> Add support for py10
